services:
  - type: web
    name: blink-backend
    runtime: node
    buildCommand: npm install && npm install --prefix server
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5002
      - key: JWT_SECRET
        value: blink_secret_key_2024
